module.exports = {
  'bc_history_head': 'Implementation Notes',
  'bc_icon_name_altname': 'Alternate Name',
  'bc_icon_name_chrome': 'Chrome',
  'bc_icon_name_chrome_android': 'Chrome for Android',
  'bc_icon_name_deprecated': 'Deprecated',
  'bc_icon_name_desktop': 'Desktop',
  'bc_icon_name_disabled': 'Disabled',
  'bc_icon_name_edge': 'Edge',
  'bc_icon_name_edge_mobile': 'Edge Mobile',
  'bc_icon_name_experimental': 'Experimental',
  'bc_icon_name_firefox': 'Firefox',
  'bc_icon_name_firefox_android': 'Firefox for Android',
  'bc_icon_name_footnote': 'Notes',
  'bc_icon_name_ie': 'Internet Explorer',
  'bc_icon_name_mobile': 'Mobile',
  'bc_icon_name_nodejs': 'Node.js',
  'bc_icon_name_non-standard': 'Non-standard',
  'bc_icon_name_opera': 'Opera',
  'bc_icon_name_opera_android': 'Opera for Android',
  'bc_icon_name_prefix': 'Prefixed',
  'bc_icon_name_safari': 'Safari',
  'bc_icon_name_safari_ios': 'iOS Safari',
  'bc_icon_name_samsunginternet_android': 'Samsung Internet',
  'bc_icon_name_server': 'Server',
  'bc_icon_name_webview_android': 'Android webview',
  'bc_icon_title_altname': 'Uses the non-standard name: <code>$1$</code>',
  'bc_icon_title_deprecated': 'Deprecated. Not for use in new websites.',
  'bc_icon_title_disabled': 'User must explicitly enable this feature.',
  'bc_icon_title_experimental': 'Experimental. Expect behavior to change in the future.',
  'bc_icon_title_footnote': 'See implementation notes',
  'bc_icon_title_non-standard': 'Non-standard. Expect poor cross-browser support.',
  'bc_icon_title_prefix': 'Requires the vendor prefix: $1$',
  'feature': 'Feature',
  'feature_basicsupport': 'Basic support',
  'legend': 'Legend',
  'legend_altname': 'Uses a non-standard name.',
  'legend_deprecated': 'Deprecated. Not for use in new websites.',
  'legend_disabled': 'User must explicitly enable this feature.',
  'legend_experimental': 'Experimental. Expect behavior to change in the future.',
  'legend_footnote': 'See implementation notes.',
  'legend_non-standard': 'Non-standard. Expect poor cross-browser support.',
  'legend_prefix': 'Requires a vendor prefix or different name for use.',
  'supportsLong_no': 'No support',
  'supportsLong_partial': 'Partial support',
  'supportsLong_unknown': 'Compatibility unknown',
  'supportsLong_yes': 'Full support',
  'supportsShort_no': 'No',
  'supportsShort_partial': 'Partial',
  'supportsShort_unknown': '?',
  'supportsShort_unknown_title': 'Compatibility unknown; please update this.',
  'supportsShort_yes': 'Yes',
  'supportsShort_yes_title': 'Please update this with the earliest version of support.',
  'no_data_found': 'No compatibility data found. Please contribute data for "${query}" (depth: ${depth}) to the <a href="https://github.com/mdn/browser-compat-data">MDN compatibility data repository</a>.'
}
